"""empty message

Revision ID: 0d7ea45b94f8
Revises: cd58dc65cae8
Create Date: 2024-11-05 13:16:07.246514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d7ea45b94f8'
down_revision: Union[str, None] = 'cd58dc65cae8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('forbidden_word_employee_id_fkey', 'forbidden_word', type_='foreignkey')
    op.drop_constraint('forbidden_word_category_id_fkey', 'forbidden_word', type_='foreignkey')
    op.create_foreign_key(None, 'forbidden_word', 'category', ['category_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'forbidden_word', 'employee', ['employee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'forbidden_word', type_='foreignkey')
    op.drop_constraint(None, 'forbidden_word', type_='foreignkey')
    op.create_foreign_key('forbidden_word_category_id_fkey', 'forbidden_word', 'category', ['category_id'], ['id'])
    op.create_foreign_key('forbidden_word_employee_id_fkey', 'forbidden_word', 'employee', ['employee_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
