"""empty message

Revision ID: 5e6af78bce9c
Revises: 9b926afa0d86
Create Date: 2024-11-04 11:00:52.897715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e6af78bce9c'
down_revision: Union[str, None] = '9b926afa0d86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forbidden_word', sa.Column('category_id', sa.BigInteger(), nullable=False))
    op.create_foreign_key(None, 'forbidden_word', 'category', ['category_id'], ['id'])
    op.drop_column('forbidden_word', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forbidden_word', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'forbidden_word', type_='foreignkey')
    op.drop_column('forbidden_word', 'category_id')
    # ### end Alembic commands ###
