"""empty message

Revision ID: 6ccf3e777863
Revises: 8922be2f6251
Create Date: 2024-10-11 17:06:03.847180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ccf3e777863'
down_revision: Union[str, None] = '8922be2f6251'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'forbidden_word', ['word'])
    op.drop_column('forbidden_word', 'answer')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forbidden_word', sa.Column('answer', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'forbidden_word', type_='unique')
    # ### end Alembic commands ###
