"""empty message

Revision ID: 9b926afa0d86
Revises: 626384dba4dd
Create Date: 2024-11-04 10:48:10.792301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b926afa0d86'
down_revision: Union[str, None] = '626384dba4dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forbidden_word', sa.Column('category', sa.String(), nullable=False))
    op.drop_constraint('forbidden_word_category_id_fkey', 'forbidden_word', type_='foreignkey')
    op.drop_column('forbidden_word', 'category_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forbidden_word', sa.Column('category_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.create_foreign_key('forbidden_word_category_id_fkey', 'forbidden_word', 'category', ['category_id'], ['id'])
    op.drop_column('forbidden_word', 'category')
    # ### end Alembic commands ###
