"""empty message

Revision ID: c450719d3640
Revises: 08a5ff19ea44
Create Date: 2024-10-22 12:01:34.788888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c450719d3640'
down_revision: Union[str, None] = '08a5ff19ea44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('employee_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('forbidden_word', sa.Column('answer', sa.String(), nullable=False))
    op.add_column('forbidden_word', sa.Column('category_id', sa.BigInteger(), nullable=False))
    op.create_foreign_key(None, 'forbidden_word', 'category', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'forbidden_word', type_='foreignkey')
    op.drop_column('forbidden_word', 'category_id')
    op.drop_column('forbidden_word', 'answer')
    op.drop_table('category')
    # ### end Alembic commands ###
