"""empty message

Revision ID: cd10367bc520
Revises: 0d7ea45b94f8
Create Date: 2024-11-05 15:20:56.697705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd10367bc520'
down_revision: Union[str, None] = '0d7ea45b94f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('category', 'employee_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_constraint('category_employee_id_fkey', 'category', type_='foreignkey')
    op.create_foreign_key(None, 'category', 'employee', ['employee_id'], ['id'], ondelete='SET NULL')
    op.alter_column('forbidden_word', 'employee_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('forbidden_word', 'category_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_constraint('forbidden_word_employee_id_fkey', 'forbidden_word', type_='foreignkey')
    op.create_foreign_key(None, 'forbidden_word', 'employee', ['employee_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'forbidden_word', type_='foreignkey')
    op.create_foreign_key('forbidden_word_employee_id_fkey', 'forbidden_word', 'employee', ['employee_id'], ['id'])
    op.alter_column('forbidden_word', 'category_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('forbidden_word', 'employee_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_constraint(None, 'category', type_='foreignkey')
    op.create_foreign_key('category_employee_id_fkey', 'category', 'employee', ['employee_id'], ['id'])
    op.alter_column('category', 'employee_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
