"""empty message

Revision ID: cd58dc65cae8
Revises: 5e6af78bce9c
Create Date: 2024-11-05 13:15:30.097764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd58dc65cae8'
down_revision: Union[str, None] = '5e6af78bce9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('forbidden_word_employee_id_fkey', 'forbidden_word', type_='foreignkey')
    op.create_foreign_key(None, 'forbidden_word', 'employee', ['employee_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'forbidden_word', type_='foreignkey')
    op.create_foreign_key('forbidden_word_employee_id_fkey', 'forbidden_word', 'employee', ['employee_id'], ['id'])
    # ### end Alembic commands ###
